name: shapeformer
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=10.1
  - python>=3.7.0
  - pip
  - cython>=0.29.0
  - jupyterlab
  - ipykernel
# need this command afterward
# ipython kernel install --user --name=<any_name_for_kernel>

# numpy universe
  - numpy>=1.16.5
  - matplotlib>=3.0.3
  - pandas>=0.23.4
  - scikit-learn
  - scikit-image>=0.14.1
  - scipy>=1.1.0
# deep learning 
  - pytorch::pytorch==1.7.0
  - pytorch::torchvision==0.8.0
  - pytorch::torchaudio==0.7.0
  - conda-forge::pytorch-lightning==1.3.8
  - conda-forge::torchmetrics==0.5.0
#  - tensorboardx>=2.0
#  - tensorboard>=2.0
#  changed tensorboard to wandb
# system, file io, testing
  - pytest>=4.0.2
  - tqdm>=4.28.1
  - pyyaml>=3.13
  - h5py>=2.9.0
  - bashlex
  - pathos
  - nb_conda_kernels
# geometry
  - conda-forge::igl>2.2.0
  - trimesh>=3.7.4
  - plyfile>=0.7
# rendering, image and video processing
  - ffmpeg
  - libiconv
  - pillow=5.3.0
  - fresnel
  - imageio=2.4.1
  - pip:
    - PyMCubes
    - wandb
    - einops
